- name: Demo on variables
  hosts: localhost
  become: yes
  tasks:
    - name: print a message
      ansible.builtin.debug:
        msg: hello Tanvi


- name: Print a variable
  hosts: localhost
  become: yes
#variable declared on play level
  vars:
    url: example.com
  tasks:
    - name: Print variable
      ansible.builtin.debug:
        msg: "{{ url }}"

    - name: Print a variable declared on task level
      ansible.builtin.debug:
       msg: "{{ url }}"
      vars:
        url: play.example.com
- name: demo on roles
  host:
  roles:
    - demorole

